all: clear driver1 driver2

clear:
	@clear

driver1:
	@g++ -std=c++11 driver1.cpp tetromino.cpp tetris.cpp -o main1.out
	@./main1.out

driver2:
	@g++ -std=c++11 driver2.cpp tetromino.cpp tetris.cpp -o main2.out
	@./main2.out
